name: test_mop_win11_uma
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.12.7
 - pip
 - setuptools
 - wheel
 - pip:
     - absl-py==2.3.1
     - annotated-types==0.7.0
     - antlr4-python3-runtime==4.9.3
     - ase==3.26.0
     - ase-db-backends==0.10.0
     - bibtexparser==1.4.3
     - certifi==2025.8.3
     - cffi==1.17.1
     - charset-normalizer==3.4.2
     - click==8.2.1
     - cloudpickle==3.1.1
     - clusterscope==0.0.12
     - colorama==0.4.6
     - contourpy==1.3.3
     - cryptography==45.0.6
     - cycler==0.12.1
     - e3nn==0.5.6
     - fairchem-core==2.7.1
     - filelock==3.18.0
     - fonttools==4.59.0
     - fsspec==2025.7.0
     - gitdb==4.0.12
     - gitpython==3.1.45
     - grpcio==1.74.0
     - huggingface-hub==0.34.3
     - hydra-core==1.3.2
     - idna==3.10
     - jax==0.7.2
     - jaxlib==0.7.2
     - jinja2==3.1.6
     - joblib==1.5.1
     - kiwisolver==1.4.8
     - llvmlite==0.44.0
     - lmdb==1.7.3
     - markdown==3.8.2
     - markupsafe==3.0.2
     - matplotlib==3.10.5
     - ml-dtypes==0.5.3
     - monty==2025.3.3
     - mpmath==1.3.0
     - mypy-extensions==1.1.0
     - narwhals==2.0.1
     - networkx==3.5
     - numba==0.61.2
     - numpy==2.2.6
     - omegaconf==2.3.0
     - opt-einsum==3.4.0
     - opt-einsum-fx==0.1.4
     - orjson==3.11.1
     - packaging==25.0
     - palettable==3.3.3
     - pandas==2.3.1
     - pillow==11.3.0
     - platformdirs==4.3.8
     - plotly==6.2.0
     - protobuf==6.31.1
     - psutil==7.0.0
     - psycopg2-binary==2.9.10
     - pycparser==2.22
     - pydantic==2.11.7
     - pydantic-core==2.33.2
     - pygfn0==0.0.3
     - pymatgen==2025.10.7
     - pymysql==1.1.1
     - pyparsing==3.2.3
     - pyre-extensions==0.0.32
     - python-dateutil==2.9.0.post0
     - pytz==2025.2
     - pyyaml==6.0.2
     - requests==2.32.4
     - ruamel-yaml==0.18.14
     - ruamel-yaml-clib==0.2.12
     - scipy==1.16.3
     - sella==2.3.5
     - sentry-sdk==2.34.1
     - six==1.17.0
     - smmap==5.0.2
     - spglib==2.6.0
     - submitit==1.5.3
     - sympy==1.13.1
     - tabulate==0.9.0
     - tensorboard==2.20.0
     - tensorboard-data-server==0.7.2
     - torch==2.6.0
     - torchtnt==0.2.4
     - tqdm==4.67.1
     - typing-extensions==4.14.1
     - typing-inspect==0.9.0
     - typing-inspection==0.4.1
     - tzdata==2025.2
     - uncertainties==3.2.3
     - urllib3==2.5.0
     - wandb==0.21.0
     - websockets==15.0.1
     - werkzeug==3.1.3