name: test_mop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.7 
  - pip
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - ase==3.26.0
      - ase-db-backends==0.11.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - clusterscope==0.0.12
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - e3nn==0.5.8
      - fairchem-core==2.7.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.7
      - hydra-core==1.3.2
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.5
      - monty==2025.3.3
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.6
      - numba==0.62.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.11.4
      - packaging==25.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - psycopg2-binary==2.9.11
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pymysql==1.1.2
      - pyparsing==3.2.5
      - pyre-extensions==0.0.32
      - pyscf==2.9.0
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - scipy==1.13.1
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - submitit==1.5.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblite==0.4.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.6.0
      - torchtnt==0.2.4
      - tqdm==4.67.1
      - triton==3.2.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - wandb==0.23.1
      - websockets==15.0.1
      - werkzeug==3.1.4
